#!/bin/bash
set -e

echo "Creating registry user and database..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${PSQL_REGISTRY_USERNAME} WITH PASSWORD '${PSQL_REGISTRY_PASSWORD}';
    CREATE DATABASE ${PSQL_REGISTRY_DATABASE} OWNER ${PSQL_REGISTRY_USERNAME};
    GRANT ALL PRIVILEGES ON DATABASE ${PSQL_REGISTRY_DATABASE} TO ${PSQL_REGISTRY_USERNAME};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${PSQL_REGISTRY_DATABASE}" <<-EOSQL
    GRANT ALL ON SCHEMA public TO ${PSQL_REGISTRY_USERNAME};
EOSQL

echo "Registry database initialization completed"
