#!/bin/bash
set -e

echo "Creating identity user and database..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${PSQL_IDENTITY_USERNAME} WITH PASSWORD '${PSQL_IDENTITY_PASSWORD}';
    CREATE DATABASE ${PSQL_IDENTITY_DATABASE} OWNER ${PSQL_IDENTITY_USERNAME};
    GRANT ALL PRIVILEGES ON DATABASE ${PSQL_IDENTITY_DATABASE} TO ${PSQL_IDENTITY_USERNAME};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${PSQL_IDENTITY_DATABASE}" <<-EOSQL
    GRANT ALL ON SCHEMA public TO ${PSQL_IDENTITY_USERNAME};
EOSQL

echo "Identity database initialization completed"
